import { ScheduleHeaders } from "../components/Schedule";

export const HEADER_TYPES: ScheduleHeaders = {
  cOrder: {
    key: "order",
    validity: false,
    value: [
      "Số thứ tự",
      "tt",
      "TT",
      "stt",
      "STT",
      "Số TT",
      "Số Thứ Tự",
      "So TT",
      "So Thu Tu",
      "So thu tu",
      "Soá TT",
      "Soá Thöù Töï",
      "Soá thöù töï",
      "Số TT",
      "Số Thứ Tự",
      "Số thứ tự",
    ],
    regex: /\d+/gmu,
  },
  cId: {
    key: "id",
    validity: false,
    value: [
      "Lớp học phần",
      "LHP",
      "Lớp HP",
      "Lớp Học Phần",
      "Lop HP",
      "Lop Hoc Phan",
      "Lop hoc phan",
      "Lôùp HP",
      "Lôùp Hoïc Phaàn",
      "Lôùp hoïc phaàn",
      "Lớp HP",
      "Lớp Học Phần",
      "Lớp học phần",
    ],
    regex: /[^\r\n\t\f\v]+/gmu,
  },
  cGroup: {
    key: "group",
    validity: false,
    value: [
      "Nhóm thảo luận",
      "NTL",
      "Nhóm TL",
      "Nhóm Thảo Luận",
      "Nhom TL",
      "Nhom Thao Luan",
      "Nhom thao luan",
      "Nhoùm TL",
      "Nhoùm Thaûo Luaän",
      "Nhoùm thaûo luaän",
      "Nhóm TL",
      "Nhóm Thảo Luận",
      "Nhóm thảo luận",
    ],
    regex: /[^\r\n\t\f\v]+/gmu,
  },
  cName: {
    key: "name",
    validity: false,
    value: [
      "Tên học phần",
      "THP",
      "Tên HP",
      "Tên Học Phần",
      "Ten HP",
      "Ten Hoc Phan",
      "Ten hoc phan",
      "Teân HP",
      "Teân Hoïc Phaàn",
      "Teân hoïc phaàn",
      "Tên HP",
      "Tên Học Phần",
      "Tên học phần",
    ],
    regex: /[^\r\n\t\f\v]+/gmu,
  },
  cType: {
    key: "type",
    validity: false,
    value: [
      "Loại học phần",
      "LHP",
      "Loại HP",
      "Loại Học Phần",
      "Loai HP",
      "Loai Hoc Phan",
      "Loai hoc phan",
      "Loaïi HP",
      "Loaïi Hoïc Phaàn",
      "Loaïi hoïc phaàn",
      "Loại HP",
      "Loại Học Phần",
      "Loại học phần",
    ],
    regex: /[^\r\n\t\f\v]+/gmu,
  },
  cDates: {
    key: "dates",
    validity: false,
    value: ["Thứ", "Thu", "Thöù", "Thứ"],
    regex: /[^\r\n\t\f\v]+/gmu,
  },
  cPeriods: {
    key: "periods",
    validity: false,
    value: ["Tiết", "Tiet", "Tieát", "Tiết"],
    regex: /[-_]*([-_]*\d+[-_]*)+/g,
  },
  cRoom: {
    key: "room",
    validity: false,
    value: ["Phòng", "Phong", "Phoøng", "Phòng"],
    regex: /[^\r\n\t\f\v]+/gmu,
  },
  cWeeks: {
    key: "weeks",
    validity: false,
    value: ["Tuần học", "Tuan hoc", "Tuaàn hoïc", "Tuần học"],
    regex: /[-_]*([-_]*\d+[-_]*)+/g,
  },
};
